### ISSUE TITLE
local mode looses error messages and loops forever

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/crank#68]
Following https://github.com/dotnet/crank/blob/master/docs/local_application.md I malevolently put a syntax error into samples/hello/Program.cs and run the crank. (I am not using code to edit c#, but plain old vi.)

I don't see where the error messages end up.  I can't find a log file.  The error messages don't seem to come out on stderr.
The crank engine spits out this string once per second, for 3 minutes, before complaining that the job didn't start.

[09:51:30.228] Processing job 'application' (9) in state Starting

**Comment by jmezach** [comment]
I'm having a similar issue, except that as far as I know I don't have any syntax error in my app. It builds and runs just fine when I run it locally using dotnet run. I'm guessing there's something going wrong during startup, but I don't see any output from that anywhere.

**Comment by jmezach** [comment]
I installed Crank on my machine today using the documented instructions. If that gets me the latest version then I think it has not been fixed unfortunately. Or do I need to do something special to get the latest build?

**Comment by sebastienros** [comment]
Thanks, the change was in the agent. I did the change on Friday and someone provided a fix related to it yesterday.

Can you share your project file? I want to see how you specified the assembly name.
Relevant code:
https://github.com/dotnet/crank/blob/master/src/Microsoft.Crank.Agent/Startup.cs#L2577-L2592

**Comment by jmezach** [comment]
I've defined it as follows:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyName>RR.ApiGateway</AssemblyName>
    ...
  </PropertyGroup>
  ...
</Project>
```

If I look at that code I would say that would work.

**Comment by sebastienros** [comment]
Ah, I thought you were using the code one.

I will update the package soon and let you know. You can try with the source in the meantime.

**Comment by sebastienros** [comment]
Fixed

**Comment by jmezach** [comment]
@sebastienros Does your comment mean you've updated the package, because I'm still seeing a version from 19 days ago up on NuGet? Or are you referring to the code fix?
